# Generated by Django 2.0.2 on 2020-05-29 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='sub_unit',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='unit',
        ),
        migrations.AddField(
            model_name='enterprisetype',
            name='unit',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise'),
        ),
    ]
