# Generated by Django 2.0.2 on 2020-05-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20200530_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'verbose_name_plural': 'Enterprises'},
        ),
        migrations.AlterModelOptions(
            name='enterprisetype',
            options={'verbose_name_plural': 'Enterprise Types'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
