# Generated by Django 2.0.2 on 2020-06-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20200530_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_section', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Enterprise Units',
            },
        ),
        migrations.RenameField(
            model_name='enterprise',
            old_name='type',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='enterprisetype',
            old_name='products',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='enterprisetype',
            name='unit',
        ),
        migrations.AddField(
            model_name='enterpriseunit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseType'),
        ),
    ]
