# Generated by Django 2.0.2 on 2020-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_auto_20200603_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentmode', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Payment Modes',
            },
        ),
        migrations.RemoveField(
            model_name='enterpriseunit',
            name='category',
        ),
        migrations.DeleteModel(
            name='EnterpriseUnit',
        ),
    ]
