# Generated by Django 2.0.2 on 2020-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_auto_20200627_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layerseggslosses',
            old_name='eggs_stock_actual',
            new_name='eggs_stock_actual_crates',
        ),
        migrations.RemoveField(
            model_name='layerseggslosses',
            name='loss_type',
        ),
        migrations.RemoveField(
            model_name='layerseggslosses',
            name='quantity_lost',
        ),
        migrations.RemoveField(
            model_name='layerseggslosses',
            name='unit',
        ),
        migrations.AddField(
            model_name='layerseggslosses',
            name='egg_loss_breakages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='layerseggslosses',
            name='egg_loss_defects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='layerseggslosses',
            name='egg_loss_unaccounted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='layerseggslosses',
            name='eggs_stock_actual_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
