# Generated by Django 2.0.2 on 2020-06-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_auto_20200627_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayersCashPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_type', models.CharField(max_length=255)),
                ('cash_point', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Layers Cash Points',
            },
        ),
        migrations.AlterField(
            model_name='layerseggsinventory',
            name='egg_loss_breakages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='layerseggsinventory',
            name='egg_loss_defects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='layerseggsinventory',
            name='egg_loss_unaccounted',
            field=models.IntegerField(),
        ),
    ]
