# Generated by Django 2.0.2 on 2020-06-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_auto_20200628_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersexpenses',
            name='cashpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='layers.LayersCashPoints', verbose_name='payment_point'),
            preserve_default=False,
        ),
    ]
