# Generated by Django 2.0.2 on 2020-06-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0007_layerscashdeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerscashdeposit',
            name='amount',
        ),
        migrations.AddField(
            model_name='layerscashdeposit',
            name='cash_balance',
            field=models.DecimalField(decimal_places=0, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layerscashdeposit',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=0, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
