# Generated by Django 2.0.2 on 2020-06-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0008_auto_20200629_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerscashdeposit',
            name='cashpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.LayersCashPoints', verbose_name='deposit_point'),
        ),
        migrations.AlterField(
            model_name='layerscashdeposit',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
