# Generated by Django 2.0.2 on 2020-07-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_auto_20200630_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerscashdeposit',
            name='cashpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.LayersCashPoints', verbose_name='deposit_point'),
        ),
        migrations.AlterField(
            model_name='layersexpenses',
            name='vendor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='layers.LayersVendors', verbose_name='vendor'),
        ),
    ]
