# Generated by Django 2.0.2 on 2020-07-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0012_auto_20200705_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerscashdeposit',
            name='cash_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
