# Generated by Django 2.0.2 on 2020-07-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_auto_20200603_0217'),
        ('layers', '0013_auto_20200705_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayersCreditManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_date', models.DateField()),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.LayersSales', verbose_name='customer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Staff', verbose_name='depositor')),
            ],
            options={
                'verbose_name_plural': 'Layers Deposit',
                'ordering': ['-installment_date'],
            },
        ),
    ]
