# Generated by Django 2.0.2 on 2020-06-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0005_auto_20200603_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayersCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Layers Customers',
                'ordering': ['-reg_date'],
            },
        ),
        migrations.CreateModel(
            name='LayersInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('stock_in', models.IntegerField()),
                ('stock_out', models.IntegerField()),
                ('stock_movement_type', models.CharField(max_length=255)),
                ('stock_movement_notes', models.CharField(max_length=255)),
                ('enterprise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseType', verbose_name='enterprise_type')),
            ],
            options={
                'verbose_name_plural': 'Layers Inventory',
            },
        ),
        migrations.CreateModel(
            name='LayersProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_date', models.DateField()),
                ('birds', models.IntegerField()),
                ('gross', models.IntegerField()),
                ('defects', models.IntegerField()),
                ('broken', models.IntegerField()),
                ('enterprise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseType', verbose_name='enterprise_type')),
            ],
            options={
                'verbose_name_plural': 'Layers Production',
            },
        ),
        migrations.CreateModel(
            name='LayersProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('unit_measure', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Layers Products',
            },
        ),
        migrations.CreateModel(
            name='LayersSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.LayersCustomers', verbose_name='customer')),
                ('enterprise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseType', verbose_name='enterprise_type')),
                ('paymentmode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.PaymentModes', verbose_name='payment_mode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.LayersProducts', verbose_name='product')),
            ],
            options={
                'verbose_name_plural': 'Layers Sales',
            },
        ),
        migrations.CreateModel(
            name='LayersSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('sub_section', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_sub_section', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Layers Units',
            },
        ),
        migrations.AddField(
            model_name='layerssales',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.LayersSection', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='layerssales',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Staff', verbose_name='staff'),
        ),
        migrations.AddField(
            model_name='layersproduction',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.LayersSection', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='layersproduction',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Staff', verbose_name='staff'),
        ),
        migrations.AddField(
            model_name='layersinventory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.LayersSection', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='layersinventory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Staff', verbose_name='staff'),
        ),
    ]
