# Generated by Django 2.0.2 on 2020-06-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layersinventory',
            name='enterprise_type',
        ),
        migrations.RemoveField(
            model_name='layersinventory',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='layersproduction',
            name='enterprise_type',
        ),
        migrations.RemoveField(
            model_name='layersproduction',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='layerssales',
            name='enterprise_type',
        ),
        migrations.RemoveField(
            model_name='layerssales',
            name='paymentmode',
        ),
        migrations.RemoveField(
            model_name='layerssales',
            name='staff',
        ),
    ]
