# Generated by Django 2.0.2 on 2020-04-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
