# Generated by Django 2.0.2 on 2020-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200419_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='date',
            new_name='reg_date',
        ),
        migrations.AddField(
            model_name='customers',
            name='laststname',
            field=models.CharField(default='Wally', max_length=255),
        ),
    ]
