# Generated by Django 2.0.2 on 2020-04-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200419_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='laststname',
            new_name='lasttname',
        ),
    ]
