# Generated by Django 2.0.2 on 2020-04-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200419_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
