# Generated by Django 2.0.2 on 2020-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200419_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
