# Generated by Django 2.0.2 on 2020-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customers_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customername',
            field=models.CharField(default='Wally', max_length=255),
        ),
    ]
