# Generated by Django 2.0.2 on 2020-05-14 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20200419_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='customername',
        ),
        migrations.AlterField(
            model_name='customers',
            name='firstname',
            field=models.CharField(default='Wally', max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='location',
            field=models.CharField(blank=True, default='Nakuru', max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phonenumber',
            field=models.CharField(default='0721620642', max_length=10, validators=[django.core.validators.RegexValidator('^(05)\\d{9}$', 'Phone number must be entered in the format: 0722000000')]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='reg_date',
            field=models.DateField(default='2020-05-08'),
        ),
        migrations.AlterModelTable(
            name='customers',
            table='customers_customers',
        ),
    ]
