# Generated by Django 2.0.2 on 2020-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salesperson', models.CharField(max_length=255)),
                ('paymentmode', models.CharField(max_length=255)),
                ('unitmeasure', models.CharField(max_length=255)),
                ('units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
