# Generated by Django 2.0.2 on 2020-04-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200419_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
